[package]
name = "vtuber-avatar"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
description = "Bevy and bevy_vrm1 adapter for RusTuberV."

[dependencies]
vtuber-core = { path = "../vtuber-core" }
vtuber-tracking = { path = "../vtuber-tracking" }
nalgebra = "=0.35.0"
rand = { version = "=0.10.2", default-features = false }
parry3d = { package = "parry3d-f64", version = "=0.31.1", default-features = false, features = ["required-features", "std", "alloc"] }
anyhow = "1"
serde_json = "1"
bevy = { workspace = true }
bevy_vrm1 = { workspace = true, features = ["log"] }
indexmap = "2"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
bevy = { workspace = true, features = ["debug"] }
toml = "0.9"

[lints]
workspace = true
