// Generated by tools/research/convert_cmu_shoulder_limits.py.
// CMU data provenance and hashes: cmu_shoulder_rom.json.
pub(super) const SHOULDER_ROM: [[f32; 5]; 13] = [
    [1.0, 0.0, 0.0, -2.7297215, 2.6075778],
    [0.0, 1.0, 0.0, -2.213418, 2.22586],
    [0.0, 0.0, 1.0, -2.1456003, 2.0282538],
    [0.57735026, 0.57735026, 0.57735026, -2.5461566, 2.1889565],
    [-0.57735026, 0.57735026, 0.57735026, -2.8269968, 2.8239405],
    [-0.57735026, -0.57735026, 0.57735026, -3.0196867, 3.06388],
    [0.57735026, -0.57735026, 0.57735026, -2.2925532, 2.2322042],
    [0.0, std::f32::consts::FRAC_1_SQRT_2, std::f32::consts::FRAC_1_SQRT_2, -1.9293575, 1.9264623],
    [0.0, -std::f32::consts::FRAC_1_SQRT_2, std::f32::consts::FRAC_1_SQRT_2, -2.3052952, 2.186723],
    [std::f32::consts::FRAC_1_SQRT_2, 0.0, std::f32::consts::FRAC_1_SQRT_2, -2.0763357, 1.5323858],
    [-std::f32::consts::FRAC_1_SQRT_2, 0.0, std::f32::consts::FRAC_1_SQRT_2, -2.8958366, 2.8143318],
    [std::f32::consts::FRAC_1_SQRT_2, std::f32::consts::FRAC_1_SQRT_2, 0.0, -3.0926604, 3.075437],
    [-std::f32::consts::FRAC_1_SQRT_2, std::f32::consts::FRAC_1_SQRT_2, 0.0, -3.0981152, 3.0984168],
];
