//! Builds the third-party license inventory from `Cargo.lock`.
//!
//! Every crate outside this repository is grouped by the SPDX expression its
//! published manifest declares, and the license files that crate ships at its
//! package root are copied out verbatim. Nothing here translates or rewrites a
//! license body; the generated file only points at the upstream bytes.

#![allow(missing_docs)]

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Name, version, and origin of one `Cargo.lock` package.
struct LockedPackage {
    name: String,
    version: String,
    source: String,
}

/// One license document copied verbatim out of a crate package.
struct Text {
    file_name: String,
    body: String,
}

/// Every item that declares the same SPDX license expression.
struct Group {
    expression: String,
    items: Vec<(String, String)>,
    texts: Vec<Text>,
}

impl Group {
    /// Keep one copy per distinct body, labelled with the smallest file name
    /// that carried it.
    fn push_text(&mut self, text: Text) {
        match self
            .texts
            .iter_mut()
            .find(|existing| existing.body == text.body)
        {
            Some(existing) => {
                if text.file_name < existing.file_name {
                    existing.file_name = text.file_name;
                }
            }
            None => self.texts.push(text),
        }
    }
}

/// File name prefixes Cargo packages use for their license and notice files.
const LICENSE_FILE_PREFIXES: [&str; 4] = ["LICENSE", "LICENCE", "COPYING", "NOTICE"];

/// Generated file layout consumed by `src/licenses.rs`.
const GENERATED_FILE: &str = "oss_licenses.rs";
const TEXT_DIRECTORY: &str = "license_texts";

const GENERATED_HEADER: &str = r#"// @generated by build.rs from Cargo.lock and the crate sources. Do not edit.

/// One distributed item: a crate, or an asset this repository ships.
pub struct LicensedItem {
    /// Item name, for example `bevy` or `LINESeedJP_A_TTF_Rg.ttf`.
    pub name: &'static str,
    /// Version, or an empty string when the item carries none.
    pub version: &'static str,
}

/// One license document, reproduced verbatim from the file it came from.
pub struct LicenseText {
    /// Upstream file name, for example `LICENSE-APACHE`.
    pub file_name: &'static str,
    /// Verbatim license body.
    pub body: &'static str,
}

/// Every item that declares one SPDX license expression.
pub struct LicenseGroup {
    /// SPDX license expression, for example `MIT OR Apache-2.0`.
    pub expression: &'static str,
    /// Items covered by this expression.
    pub items: &'static [LicensedItem],
    /// Distinct license documents found for this expression.
    pub texts: &'static [LicenseText],
}

/// Crates from outside this repository, grouped by license expression.
pub static DEPENDENCY_LICENSE_GROUPS: &[LicenseGroup] = &[
"#;

fn main() -> Result<(), String> {
    println!("cargo:rerun-if-env-changed=CARGO_HOME");
    generate().map_err(|error| format!("cannot build the third-party license inventory: {error}"))
}

fn generate() -> Result<(), String> {
    let out_dir = PathBuf::from(
        env::var_os("OUT_DIR").ok_or_else(|| "OUT_DIR is not set by Cargo".to_string())?,
    );
    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR")
            .ok_or_else(|| "CARGO_MANIFEST_DIR is not set by Cargo".to_string())?,
    );
    let workspace_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .ok_or_else(|| {
            format!(
                "cannot derive the workspace root from {}",
                manifest_dir.display()
            )
        })?
        .to_path_buf();
    let lock_path = workspace_root.join("Cargo.lock");
    println!("cargo:rerun-if-changed={}", lock_path.display());
    let lock = fs::read_to_string(&lock_path)
        .map_err(|error| format!("cannot read {}: {error}", lock_path.display()))?;

    let cargo_home = cargo_home()?;
    let mut groups: BTreeMap<String, Group> = BTreeMap::new();
    for package in locked_packages(&lock) {
        let Some(directory) = source_directory(&cargo_home, &package) else {
            println!(
                "cargo:warning=no local source for {} {}, its license is not listed",
                package.name, package.version
            );
            continue;
        };
        let manifest = fs::read_to_string(directory.join("Cargo.toml")).map_err(|error| {
            format!(
                "cannot read the manifest of {} {} at {}: {error}",
                package.name,
                package.version,
                directory.display()
            )
        })?;
        let expression = license_expression(&manifest);
        let group = groups.entry(expression.clone()).or_insert_with(|| Group {
            expression,
            items: Vec::new(),
            texts: Vec::new(),
        });
        group
            .items
            .push((package.name.clone(), package.version.clone()));
        for text in read_license_files(&directory) {
            group.push_text(text);
        }
    }

    let mut groups: Vec<Group> = groups.into_values().collect();
    for group in &mut groups {
        group.texts.sort_by(|left, right| {
            (&left.file_name, &left.body).cmp(&(&right.file_name, &right.body))
        });
    }
    let source = render(&groups, &out_dir)?;
    fs::write(out_dir.join(GENERATED_FILE), source)
        .map_err(|error| format!("cannot write the generated license file: {error}"))
}

fn cargo_home() -> Result<PathBuf, String> {
    if let Some(home) = env::var_os("CARGO_HOME") {
        return Ok(PathBuf::from(home));
    }
    let home = env::var_os("HOME")
        .or_else(|| env::var_os("USERPROFILE"))
        .ok_or_else(|| "neither CARGO_HOME nor a home directory is set".to_string())?;
    Ok(PathBuf::from(home).join(".cargo"))
}

/// Reads `name`, `version`, and `source` from every `[[package]]` block.
/// Workspace and other path packages carry no `source` and are skipped: they
/// are built from source inside this repository.
fn locked_packages(lock: &str) -> Vec<LockedPackage> {
    let mut packages = Vec::new();
    let mut current: Option<LockedPackage> = None;
    for line in lock.lines() {
        if line.starts_with("[[package]]") {
            if let Some(package) = current.take() {
                packages.push(package);
            }
            current = Some(LockedPackage {
                name: String::new(),
                version: String::new(),
                source: String::new(),
            });
            continue;
        }
        let Some(package) = current.as_mut() else {
            continue;
        };
        if let Some(value) = quoted_value(line, "name") {
            package.name = value;
        } else if let Some(value) = quoted_value(line, "version") {
            package.version = value;
        } else if let Some(value) = quoted_value(line, "source") {
            package.source = value;
        }
    }
    if let Some(package) = current {
        packages.push(package);
    }
    packages
        .into_iter()
        .filter(|package| !package.source.is_empty())
        .collect()
}

fn quoted_value(line: &str, key: &str) -> Option<String> {
    let value = line.strip_prefix(key)?.strip_prefix(" = \"")?;
    Some(value.strip_suffix('"')?.to_string())
}

/// A registry package lives in `$CARGO_HOME/registry/src/<index>/<name>-<version>`.
/// A git package lives in `$CARGO_HOME/git/checkouts/<repo>-<hash>/<short-rev>`,
/// where the short revision is the commit id from the lock file.
fn source_directory(cargo_home: &Path, package: &LockedPackage) -> Option<PathBuf> {
    let revision = package.source.split_once('#').map(|(_, revision)| revision);
    let root = match revision {
        Some(_) => cargo_home.join("git").join("checkouts"),
        None => cargo_home.join("registry").join("src"),
    };
    for repository in fs::read_dir(root).ok()?.flatten() {
        let directory = match revision {
            Some(revision) => repository.path().join(short_revision(revision)),
            None => repository
                .path()
                .join(format!("{}-{}", package.name, package.version)),
        };
        if directory.is_dir() {
            return Some(directory);
        }
    }
    None
}

fn short_revision(revision: &str) -> &str {
    let end = revision
        .char_indices()
        .nth(7)
        .map_or(revision.len(), |(index, _)| index);
    revision.get(..end).unwrap_or(revision)
}

fn license_expression(manifest: &str) -> String {
    manifest
        .lines()
        .find_map(|line| quoted_value(line, "license"))
        .unwrap_or_else(|| "unknown".to_string())
}

fn read_license_files(directory: &Path) -> Vec<Text> {
    let Ok(entries) = fs::read_dir(directory) else {
        return Vec::new();
    };
    let texts: Vec<Text> = entries
        .flatten()
        .filter(|entry| {
            let name = entry.file_name().to_string_lossy().to_uppercase();
            LICENSE_FILE_PREFIXES
                .iter()
                .any(|prefix| name.starts_with(prefix))
        })
        .filter_map(|entry| {
            let body = fs::read_to_string(entry.path()).ok()?;
            Some(Text {
                file_name: entry.file_name().to_string_lossy().into_owned(),
                body,
            })
        })
        .collect();
    texts
}

fn render(groups: &[Group], out_dir: &Path) -> Result<String, String> {
    let text_directory = out_dir.join(TEXT_DIRECTORY);
    fs::create_dir_all(&text_directory)
        .map_err(|error| format!("cannot create {}: {error}", text_directory.display()))?;
    let mut written: BTreeMap<String, usize> = BTreeMap::new();
    let mut source = String::from(GENERATED_HEADER);
    for group in groups {
        source.push_str("    LicenseGroup {\n");
        source.push_str(&format!("        expression: {:?},\n", group.expression));
        source.push_str("        items: &[");
        for (name, version) in &group.items {
            source.push_str(&format!(
                "LicensedItem {{ name: {name:?}, version: {version:?} }}, "
            ));
        }
        source.push_str("],\n        texts: &[");
        for text in &group.texts {
            let index = match written.get(text.body.as_str()) {
                Some(index) => *index,
                None => {
                    let index = written.len();
                    fs::write(
                        text_directory.join(format!("{index}.txt")),
                        text.body.as_bytes(),
                    )
                    .map_err(|error| format!("cannot write license text {index}: {error}"))?;
                    written.insert(text.body.clone(), index);
                    index
                }
            };
            source.push_str(&format!(
                "LicenseText {{ file_name: {file_name:?}, body: include_str!(concat!(env!(\"OUT_DIR\"), \"/{TEXT_DIRECTORY}/{index}.txt\")) }},\n",
                file_name = text.file_name
            ));
        }
        source.push_str("],\n    },\n");
    }
    source.push_str("];\n");
    Ok(source)
}

#[cfg(test)]
mod tests {
    use super::{license_expression, locked_packages, quoted_value, short_revision};

    #[test]
    fn reads_the_three_fields_of_a_locked_package() {
        let lock = "\
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = \"bevy\"
version = \"0.19.0\"
source = \"registry+https://github.com/rust-lang/crates.io-index\"
checksum = \"0000\"
dependencies = [
 \"bevy_asset\",
]

[[package]]
name = \"mediapipe\"
version = \"0.1.0\"
dependencies = [
 \"libc\",
]
";
        let packages = locked_packages(lock);
        assert_eq!(packages.len(), 1, "path packages are skipped");
        assert_eq!(packages.first().map(|p| p.name.as_str()), Some("bevy"));
        assert_eq!(packages.first().map(|p| p.version.as_str()), Some("0.19.0"));
    }

    #[test]
    fn only_whole_line_quoted_values_are_read() {
        assert_eq!(
            quoted_value("source = \"git+x#abc\"", "source").as_deref(),
            Some("git+x#abc")
        );
        assert_eq!(quoted_value(" \"bevy_asset\",", "name"), None);
        assert_eq!(quoted_value("license-file = \"LICENSE\"", "license"), None);
    }

    #[test]
    fn a_git_source_resolves_to_its_short_revision_directory() {
        assert_eq!(
            short_revision("6ee2f610d6c95b542a3317028da10aba26c9e8de"),
            "6ee2f61"
        );
    }

    #[test]
    fn the_manifest_license_expression_is_the_package_field() {
        let manifest = "\
[package]
name = \"egui\"
version = \"0.35.0\"
license = \"MIT OR Apache-2.0\"
";
        assert_eq!(license_expression(manifest), "MIT OR Apache-2.0");
    }
}
