[package]
publish = false
name = "vtuber-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
description = "Desktop executable for RusTuberV."

[[bin]]
name = "RusTuberV"
path = "src/main.rs"

[dependencies]
vtuber-app = { path = "../../crates/vtuber-app" }
vtuber-avatar = { path = "../../crates/vtuber-avatar" }
bevy = { workspace = true }
bevy_egui = { workspace = true }
bevy_vrm1 = { workspace = true, features = ["log"] }
directories = "5"

[build-dependencies]
winres = "0.1"

[features]
default = ["ndi-output"]
dev-synthetic-input = ["vtuber-app/dev-synthetic-input"]
ndi-output = ["vtuber-app/ndi-output"]

[dev-dependencies]

[lints]
workspace = true
