// Generated by tools/convert_hand_poses.py; angles are radians.
// UmebocDC_Hand.211010 (CC0), adapted from the left-hand muscle curves.
// Source archive SHA-256: 596dfe27f19c6cf1d47940e1ca0a370b22ce560326aaa1ad633be478226b2f68
// No Unity clips, models, textures or archive are shipped.
use std::f32::consts::{FRAC_PI_2, FRAC_PI_3, FRAC_PI_4, FRAC_PI_6, FRAC_PI_8};
use vtuber_core::arm_tracking::HandFingerPose;

pub(super) const POSES: &[(&str, HandFingerPose)] = &[
    (
        "relaxed",
        HandFingerPose {
            fingers: [
                [0.706858, 0.436332, 0.261799],
                [FRAC_PI_4, 0.698132, 0.314159],
                [FRAC_PI_4, 0.741765, 0.366519],
                [FRAC_PI_4, 0.872665, 0.261799],
            ],
            spread: [-0.174533, -0.349066, 0.279253, 0.279253],
            thumb: [0.436332, 0.305433],
            thumb_cmc: [0.0, 0.0],
            thumb_spread: 0.959931,
        },
    ),
    (
        "open",
        HandFingerPose {
            fingers: [
                [0.15708, 0.0, 0.0],
                [0.19635, 0.0, 0.0],
                [0.314159, 0.0, 0.0],
                [FRAC_PI_8, 0.0, 0.10472],
            ],
            spread: [0.174533, 0.0, -0.174533, -0.174533],
            thumb: [0.0, 0.0],
            thumb_cmc: [0.0, 0.128],
            thumb_spread: 0.890118,
        },
    ),
    (
        "soft_open",
        HandFingerPose {
            fingers: [
                [0.15708, 0.436332, 0.0],
                [0.19635, 0.436332, 0.0],
                [0.314159, 0.436332, 0.0],
                [FRAC_PI_8, 0.436332, 0.10472],
            ],
            spread: [0.174533, -0.174533, 0.174533, -0.174533],
            thumb: [0.218166, 0.0],
            thumb_cmc: [-0.37, 0.0],
            thumb_spread: 0.959931,
        },
    ),
    (
        "fist",
        HandFingerPose {
            fingers: [
                [FRAC_PI_2, 1.745329, FRAC_PI_3],
                [FRAC_PI_2, 1.745329, FRAC_PI_3],
                [FRAC_PI_2, 1.745329, FRAC_PI_3],
                [FRAC_PI_2, 1.745329, FRAC_PI_3],
            ],
            spread: [0.0, 0.0, 0.174533, 0.349066],
            thumb: [0.654498, 1.22173],
            thumb_cmc: [0.0, 0.64],
            thumb_spread: 0.610865,
        },
    ),
    (
        "soft_fist",
        HandFingerPose {
            fingers: [
                [0.942478, 1.745329, FRAC_PI_6],
                [1.413717, 1.745329, 0.628319],
                [1.492257, 1.745329, FRAC_PI_4],
                [FRAC_PI_2, 1.745329, FRAC_PI_4],
            ],
            spread: [-0.279253, -0.174533, 0.174533, 0.349066],
            thumb: [0.567232, 0.0],
            thumb_cmc: [0.0, 0.0],
            thumb_spread: 0.959931,
        },
    ),
    (
        "thumbs_up",
        HandFingerPose {
            fingers: [
                [1.178097, 1.745329, 0.942478],
                [1.492257, 1.745329, 0.733038],
                [FRAC_PI_2, 1.745329, FRAC_PI_4],
                [FRAC_PI_2, 1.745329, 0.942478],
            ],
            spread: [-0.174533, 0.0, 0.279253, 0.349066],
            thumb: [0.218166, 0.0],
            thumb_cmc: [-0.518, 0.0],
            thumb_spread: 0.959931,
        },
    ),
    (
        "point",
        HandFingerPose {
            fingers: [
                [0.15708, 0.174533, 0.0],
                [1.413717, 1.745329, FRAC_PI_4],
                [FRAC_PI_2, 1.48353, 0.994838],
                [FRAC_PI_2, 1.745329, FRAC_PI_3],
            ],
            spread: [-0.174533, -0.174533, 0.174533, 0.349066],
            thumb: [0.567232, 0.0],
            thumb_cmc: [0.222, 0.32],
            thumb_spread: FRAC_PI_4,
        },
    ),
    (
        "peace",
        HandFingerPose {
            fingers: [
                [0.15708, 0.174533, 0.0],
                [0.15708, 0.174533, 0.0],
                [1.021018, 1.745329, 0.261799],
                [1.178097, FRAC_PI_2, FRAC_PI_6],
            ],
            spread: [0.174533, -0.349066, 0.174533, 0.349066],
            thumb: [0.654498, 0.916298],
            thumb_cmc: [0.37, 0.128],
            thumb_spread: 0.890118,
        },
    ),
    (
        "fox",
        HandFingerPose {
            fingers: [
                [0.0, 0.0, 0.0],
                [1.138827, 1.396263, 0.0],
                [1.217367, 1.134464, 0.0],
                [0.0, 0.0, 0.0],
            ],
            spread: [0.0, 0.0, 0.349066, -0.349066],
            thumb: [0.567232, 0.0],
            thumb_cmc: [0.444, 0.64],
            thumb_spread: 0.610865,
        },
    ),
    (
        "horns",
        HandFingerPose {
            fingers: [
                [0.0, 0.0, 0.0],
                [1.413717, 1.745329, 0.261799],
                [1.413717, 1.745329, 0.261799],
                [FRAC_PI_8, 0.0, 0.0],
            ],
            spread: [0.174533, 0.0, 0.349066, -0.349066],
            thumb: [0.0, 0.0],
            thumb_cmc: [0.0, 0.0],
            thumb_spread: 0.959931,
        },
    ),
    (
        "shaka",
        HandFingerPose {
            fingers: [
                [1.178097, 1.745329, 0.366519],
                [1.413717, 1.745329, 0.261799],
                [1.256637, 1.745329, 0.261799],
                [0.549779, 0.0, 0.10472],
            ],
            spread: [-0.174533, 0.0, 0.349066, -0.174533],
            thumb: [0.0, 0.0],
            thumb_cmc: [0.0, 0.0],
            thumb_spread: 0.959931,
        },
    ),
    (
        "finger_gun",
        HandFingerPose {
            fingers: [
                [0.15708, 0.0, 0.0],
                [1.178097, 1.745329, FRAC_PI_6],
                [FRAC_PI_2, 1.745329, FRAC_PI_6],
                [FRAC_PI_2, 1.745329, FRAC_PI_4],
            ],
            spread: [-0.174533, 0.0, 0.174533, 0.349066],
            thumb: [0.087266, 0.0],
            thumb_cmc: [-0.518, 0.0],
            thumb_spread: 0.959931,
        },
    ),
    (
        "three",
        HandFingerPose {
            fingers: [
                [0.314159, 0.174533, 0.0],
                [0.15708, 0.174533, 0.0],
                [FRAC_PI_8, 0.174533, 0.0],
                [1.178097, FRAC_PI_2, FRAC_PI_6],
            ],
            spread: [0.174533, -0.349066, -0.349066, 0.349066],
            thumb: [FRAC_PI_4, 0.610865],
            thumb_cmc: [0.518, 0.64],
            thumb_spread: 0.610865,
        },
    ),
    (
        "four",
        HandFingerPose {
            fingers: [
                [0.15708, 0.174533, 0.0],
                [0.235619, 0.174533, 0.0],
                [FRAC_PI_8, 0.174533, 0.0],
                [0.549779, 0.174533, 0.0],
            ],
            spread: [0.174533, -0.349066, -0.349066, -0.349066],
            thumb: [0.654498, 0.916298],
            thumb_cmc: [0.37, 0.0],
            thumb_spread: 0.959931,
        },
    ),
    (
        "finger_heart",
        HandFingerPose {
            fingers: [
                [1.413717, 0.872665, 0.10472],
                [FRAC_PI_2, 1.745329, 0.628319],
                [FRAC_PI_2, 1.745329, FRAC_PI_4],
                [FRAC_PI_2, 1.745329, FRAC_PI_4],
            ],
            spread: [-0.279253, -0.174533, 0.174533, 0.349066],
            thumb: [0.436332, 0.0],
            thumb_cmc: [0.296, 0.192],
            thumb_spread: 0.855211,
        },
    ),
    (
        "claw",
        HandFingerPose {
            fingers: [
                [0.0, 1.48353, FRAC_PI_6],
                [0.0, 1.22173, FRAC_PI_6],
                [0.0, 1.396263, FRAC_PI_6],
                [0.0, FRAC_PI_2, FRAC_PI_6],
            ],
            spread: [0.174533, -0.174533, -0.174533, -0.174533],
            thumb: [0.087266, 0.916298],
            thumb_cmc: [0.0, 0.64],
            thumb_spread: 0.610865,
        },
    ),
    (
        "chin_support",
        HandFingerPose {
            fingers: [
                [FRAC_PI_8, 0.872665, FRAC_PI_6],
                [FRAC_PI_4, 1.308997, FRAC_PI_6],
                [1.178097, 0.872665, FRAC_PI_6],
                [1.178097, 0.872665, FRAC_PI_6],
            ],
            spread: [0.0, 0.0, 0.174533, 0.174533],
            thumb: [0.349066, 0.0],
            thumb_cmc: [-0.37, 0.0],
            thumb_spread: 0.959931,
        },
    ),
    (
        "elegant",
        HandFingerPose {
            fingers: [
                [0.15708, 0.174533, 0.0],
                [0.549779, 0.872665, 0.0],
                [0.942478, 0.872665, 0.261799],
                [FRAC_PI_4, 0.872665, FRAC_PI_6],
            ],
            spread: [-0.174533, 0.0, 0.349066, 0.349066],
            thumb: [0.436332, 0.0],
            thumb_cmc: [0.0, 0.32],
            thumb_spread: FRAC_PI_4,
        },
    ),
    (
        "elegant_straight",
        HandFingerPose {
            fingers: [
                [0.15708, 0.0, 0.0],
                [0.628319, 0.0, 0.0],
                [0.942478, 0.0, 0.0],
                [1.178097, 0.0, 0.0],
            ],
            spread: [-0.174533, 0.0, 0.349066, 0.349066],
            thumb: [0.218166, 0.0],
            thumb_cmc: [0.0, 0.64],
            thumb_spread: 0.610865,
        },
    ),
    (
        "gentle_open",
        HandFingerPose {
            fingers: [
                [0.15708, 0.0, 0.0],
                [0.19635, 0.0, 0.0],
                [0.314159, 0.0, 0.0],
                [0.235619, 0.0, 0.10472],
            ],
            spread: [-0.174533, 0.0, 0.349066, 0.279253],
            thumb: [0.654498, 0.0],
            thumb_cmc: [-0.222, -0.32],
            thumb_spread: 1.134464,
        },
    ),
    (
        "ring_only",
        HandFingerPose {
            fingers: [
                [1.48353, 1.745329, FRAC_PI_3],
                [1.48353, 1.745329, FRAC_PI_3],
                [0.0, 0.0, 0.0],
                [1.48353, 1.745329, FRAC_PI_3],
            ],
            spread: [0.0, 0.0, 0.0, 0.0],
            thumb: [0.698132, FRAC_PI_3],
            thumb_cmc: [-0.349066, 0.349066],
            thumb_spread: 0.610865,
        },
    ),
    (
        "little_only",
        HandFingerPose {
            fingers: [
                [1.48353, 1.745329, FRAC_PI_3],
                [1.48353, 1.745329, FRAC_PI_3],
                [1.48353, 1.745329, FRAC_PI_3],
                [0.0, 0.0, 0.0],
            ],
            spread: [0.0, 0.0, 0.0, -0.20944],
            thumb: [0.698132, FRAC_PI_3],
            thumb_cmc: [-0.349066, 0.349066],
            thumb_spread: 0.610865,
        },
    ),
    (
        "ok",
        HandFingerPose {
            fingers: [
                [FRAC_PI_4, 1.396263, 0.610865],
                [0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0],
            ],
            spread: [0.174533, 0.0, -0.139626, -0.279253],
            thumb: [0.610865, 0.698132],
            thumb_cmc: [-0.436332, 0.349066],
            thumb_spread: 0.488692,
        },
    ),
    (
        "crossed_fingers",
        HandFingerPose {
            fingers: [
                [0.20944, 0.139626, 0.0],
                [0.087266, 0.087266, 0.0],
                [1.48353, 1.745329, FRAC_PI_3],
                [1.48353, 1.745329, FRAC_PI_3],
            ],
            spread: [-0.314159, 0.261799, 0.0, 0.0],
            thumb: [0.698132, 0.959931],
            thumb_cmc: [-0.349066, 0.349066],
            thumb_spread: 0.610865,
        },
    ),
    (
        "vulcan",
        HandFingerPose {
            fingers: [
                [0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0],
            ],
            spread: [0.244346, 0.244346, -0.244346, -0.244346],
            thumb: [0.087266, 0.0],
            thumb_cmc: [0.174533, -0.174533],
            thumb_spread: 1.134464,
        },
    ),
    (
        "half_heart",
        HandFingerPose {
            fingers: [
                [0.610865, 0.959931, 0.436332],
                [0.698132, FRAC_PI_3, FRAC_PI_6],
                [FRAC_PI_4, 1.134464, 0.610865],
                [0.872665, 1.22173, 0.698132],
            ],
            spread: [0.087266, 0.0, -0.087266, -0.174533],
            thumb: [0.174533, 0.087266],
            thumb_cmc: [-0.174533, -0.174533],
            thumb_spread: 1.22173,
        },
    ),
    (
        "three_thumb_index_middle",
        HandFingerPose {
            fingers: [
                [0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0],
                [1.48353, 1.745329, FRAC_PI_3],
                [1.48353, 1.745329, FRAC_PI_3],
            ],
            spread: [0.20944, -0.174533, 0.0, 0.0],
            thumb: [0.0, 0.0],
            thumb_cmc: [0.261799, -0.087266],
            thumb_spread: 1.134464,
        },
    ),
    (
        "i_love_you",
        HandFingerPose {
            fingers: [
                [0.0, 0.0, 0.0],
                [1.48353, 1.745329, FRAC_PI_3],
                [1.48353, 1.745329, FRAC_PI_3],
                [0.0, 0.0, 0.0],
            ],
            spread: [0.20944, 0.0, 0.0, -0.261799],
            thumb: [0.0, 0.0],
            thumb_cmc: [0.261799, -0.174533],
            thumb_spread: 1.22173,
        },
    ),
    (
        "four_with_thumb",
        HandFingerPose {
            fingers: [
                [0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0],
                [1.48353, 1.745329, FRAC_PI_3],
            ],
            spread: [0.20944, 0.0, -0.20944, 0.0],
            thumb: [0.0, 0.0],
            thumb_cmc: [0.261799, -0.087266],
            thumb_spread: 1.134464,
        },
    ),
    (
        "open_together",
        HandFingerPose {
            fingers: [
                [0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0],
            ],
            spread: [0.0, 0.0, 0.0, 0.0],
            thumb: [0.087266, 0.0],
            thumb_cmc: [0.0, 0.174533],
            thumb_spread: 0.436332,
        },
    ),
    (
        "two_together",
        HandFingerPose {
            fingers: [
                [0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0],
                [1.48353, 1.745329, FRAC_PI_3],
                [1.48353, 1.745329, FRAC_PI_3],
            ],
            spread: [0.0, 0.0, 0.0, 0.0],
            thumb: [0.698132, 0.959931],
            thumb_cmc: [-0.349066, 0.349066],
            thumb_spread: 0.610865,
        },
    ),
    (
        "pinch",
        HandFingerPose {
            fingers: [
                [FRAC_PI_6, FRAC_PI_3, 0.436332],
                [0.436332, FRAC_PI_6, 0.261799],
                [FRAC_PI_6, 0.610865, 0.349066],
                [0.610865, 0.698132, 0.436332],
            ],
            spread: [0.139626, 0.0, -0.087266, -0.174533],
            thumb: [FRAC_PI_6, 0.610865],
            thumb_cmc: [-0.349066, 0.261799],
            thumb_spread: 0.488692,
        },
    ),
];
